researches:
  class1:
    enabled: true # true / false
    type: research_any # research_any / research_all
    blueprint:
      material: book
      name: "Level 1 Research Blueprint"
      lore:
        - "&7This is a research blueprint"
    bypass-players: # allow who to bypass this blueprint, research items directly
      names:
        - "AVeryVeryLongLongLongStringToAvoidAnyPlayerNameMatchIt"
    permissions: # allow who can use this blueprint
      type: exclude_any # include_any / include_all / exclude_any / exclude_all
      nodes:
        - ""
    bind-subcommands:
      subcommands:
        - "level1" # /rb level1 can get this blueprint
    bind-items:
      regex:
        group1:
          scope-type: include # include / exclude
          scope: "addon" # addon / name / id / color_stripped_name
          value: "AVeryVeryLongLongLongStringToAvoidAnyStringMatchIt" # regex string
      items: # include only
        group1:
          scope: "id" # addon / name / id / color_stripped_name
          value:
            - ntw_blueprint #0NTW_BLUEPRINT also works
