researches:
  class1:
    enabled: true # true / false
    type: research_any # research_any / research_all
    blueprint:
      name: "Level 1 Research Blueprint"
      lore:
        - "&7This is a research blueprint"
    bypass-players: # allow who to bypass this blueprint, research items directly
      - "AVeryVeryLongLongLongStringToAvoidAnyPlayerNameMatchIt"
    permissions: # allow who can use this blueprint
      type: exclude_any # include_any / include_all / exclude_any / exclude_all
      value:
        - ""
    bind-subcommands:
      - "level1" # /rb level1 can get this blueprint
    bind-items:
      regex:
        type: include # include / exclude
        value: "AVeryVeryLongLongLongStringToAvoidAnyStringMatchIt" # regex string
      items: # include only
        type: id # id / addon
        value:
          - ntw_blueprint # NTW_BLUEPRINT also works
