name: ResearchBlueprint
author: balugaq
description: This is a plugin
main: com.balugaq.rb.implementation.ResearchBlueprintPlugin
website: https://github.com/balugaq/ResearchBlueprint
version: ${project.version}
api-version: 1.20
