name: ResearchBlueprint
author: balugaq
description: This is a plugin
main: com.balugaq.rb.implementation.ResearchBlueprintPlugin
website: https://github.com/balugaq/ResearchBlueprint
version: ${project.version}
api-version: 1.20
commands:
  rb:
    aliases: researchblueprint
    description: ResearchBlueprint base command
    usage: The ResearchBlueprint version you have installed does not seem to be compatible with your server setup. Check your console for more detailed info.
